# Project: Assignment8
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "../../../../../../Program\ Files\ (x86)/Dev-Cpp/include/graphics/ccc_msw.o" "../../../../../../Program\ Files\ (x86)/Dev-Cpp/include/graphics/ccc_shap.o" Assignment8.o
LINKOBJ  = "../../../../../../Program Files (x86)/Dev-Cpp/include/graphics/ccc_msw.o" "../../../../../../Program Files (x86)/Dev-Cpp/include/graphics/ccc_shap.o" Assignment8.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows -m32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Program Files (x86)/Dev-Cpp/include"
BIN      = Assignment8.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"../../../../../../Program\ Files\ (x86)/Dev-Cpp/include/graphics/ccc_msw.o": ../../../../../../Program\ Files\ (x86)/Dev-Cpp/include/graphics/ccc_msw.cpp
	$(CPP) -c "../../../../../../Program Files (x86)/Dev-Cpp/include/graphics/ccc_msw.cpp" -o "../../../../../../Program Files (x86)/Dev-Cpp/include/graphics/ccc_msw.o" $(CXXFLAGS)

"../../../../../../Program\ Files\ (x86)/Dev-Cpp/include/graphics/ccc_shap.o": ../../../../../../Program\ Files\ (x86)/Dev-Cpp/include/graphics/ccc_shap.cpp
	$(CPP) -c "../../../../../../Program Files (x86)/Dev-Cpp/include/graphics/ccc_shap.cpp" -o "../../../../../../Program Files (x86)/Dev-Cpp/include/graphics/ccc_shap.o" $(CXXFLAGS)

Assignment8.o: Assignment8.cpp
	$(CPP) -c Assignment8.cpp -o Assignment8.o $(CXXFLAGS)
